apiVersion: apps/v1
kind: Deployment
metadata:
  name: yash-deploy
  labels:
    app: yash-deploy-lbl
spec:
  replicas: 9
  selector:
    matchLabels:
      app: yash-app
  template:
    metadata:
      labels:
        app: yash-app
    spec:
      containers:
      - name: yash-container
        image: yash1999v/java_spring_app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: yash-np-service
  labels:
    app: yash-app
spec:
  selector:
    app: yash-app

  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
